- id: '1691288706305'
  alias: 'Vacuum: Run for 2 Hours' #This would automatically turn off the vacumm pump after two hours so it would not be left running non stop
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.vacuum
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.vacuum
  mode: single
