homeassistant:
  name: RaspiPool
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
# customize: !include customize.yaml
  packages: !include_dir_named packages
default_config:
# Disable Discover some devices automatically
# discovery:
tts:
  - platform: google_translate
logger:
  default: critical
  logs:
    homeassistant.custom_components.sensor.atlas_scientific: debug
    homeassistant.custom_components.switch.command_line: debug

# group: !include groups.yaml
# Disable automation
automation: !include automations.yaml
# script: !include scripts.yaml
lovelace:
 mode: yaml
# Telegram Bot
telegram_bot:
  - platform: polling
    api_key: #replace with your key
    allowed_chat_ids:
      - #replace with your id
# Notifier
notify:
  - platform: telegram
    name: "xxxx"
    chat_id: #replace with your id
