title: Raspipool
views:
  - badges:
      - sensor.openweathermap_temperature
      - sensor.e_fc
      - sensor.cycle_pool
      - sensor.openweathermap_condition
    title: Pool
    panel: false
    icon: 'mdi:pool'
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Analogs (60 min Avg.)
            cards:
              - max: 110
                min: 60
                theme: Backend-selected
                entity: sensor.pre_filter_temp
                segments:
                  - from: 60
                    color: '#db4437'
                  - from: 70
                    color: '#ffa600'
                  - from: 80
                    color: '#43a047'
                  - from: 90
                    color: '#ffa600'
                  - from: 100
                    color: '#db4437'
                name: Pre Filter
                type: gauge
                needle: true
              - max: 110
                min: 60
                theme: Backend-selected
                entity: sensor.post_filter_temp
                segments:
                  - from: 60
                    color: '#db4437'
                  - from: 70
                    color: '#ffa600'
                  - from: 80
                    color: '#43a047'
                  - from: 90
                    color: '#ffa600'
                  - from: 100
                    color: '#db4437'
                name: Post Heater
                type: gauge
                needle: true
              - max: 10
                min: 4
                theme: Backend-selected
                entity: sensor.ph_mean
                segments:
                  - from: 4
                    color: '#db4437'
                  - from: 6.7
                    color: '#ffa600'
                  - from: 7.0
                    color: '#43a047'
                  - from: 7.9
                    color: '#ffa600'
                  - from: 8.5
                    color: '#db4437'
                name: pH
                type: gauge
                needle: true
              - max: 1999
                min: -1000
                theme: Backend-selected
                entity: sensor.orp_mean
                segments:
                  - from: -1000
                    color: '#db4437'
                  - from: 0
                    color: '#ffa600'
                  - from: 625
                    color: '#43a047'
                  - from: 850
                    color: '#ffa600'
                  - from: 1000
                    color: '#db4437'
                name: ORP
                type: gauge
                needle: true
          - show_name: false
            title: Current Analogs
            entities:
              - entity: sensor.pre_filter_temp
                hold_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: sensor.pre_filter_temp
              - entity: sensor.ezo_ph
                hold_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: sensor.ezo_ph
              - entity: sensor.ezo_orp
                hold_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: sensor.ezo_orp
            type: glance
            show_state: true
          - title:
            type: horizontal-stack
            cards:
              - max: 20
                min: 0
                theme: default
                entity: sensor.remain_cycles
                severity:
                  green: 15
                  red: 5
                  yellow: 10
                name: Remaining Cycles
                type: gauge
              - max: 4
                min: 0
                theme: default
                entity: sensor.muriatic_tank
                severity:
                  green: 3
                  red: .5
                  yellow: 1.5
                type: gauge
              - max: 4
                min: 0
                theme: default
                entity: sensor.bleach_tank
                severity:
                  green: 3
                  red: .5
                  yellow: 1.5
                type: gauge
          - title: Control
            entities:
              - entity: switch.pump
                tap_action:
                  action: toggle
              - entity: switch.vacuum
                tap_action:
                  action: toggle      
              - entity: switch.light
                tap_action:
                  action: toggle
              - entity: binary_sensor.muriatic
                hold_action:
                  action: call-service
                  service: switch.toggle
                  service_data:
                    entity_id: switch.ph
                tap_action:
                  action: navigate
                  navigation_path: /lovelace/2
              - entity: binary_sensor.bleach
                hold_action:
                  action: call-service
                  service: switch.toggle
                  service_data:
                    entity_id: switch.orp
                tap_action:
                  action: navigate
                  navigation_path: /lovelace/2
            type: glance
            show_state: true
            show_icon: true
  - badges: []
    title: Heater
    panel: false
    icon: 'mdi:water-boiler'
    cards:
      - type: thermostat
        entity: climate.pool_heater
        name: Pool Heater
      - type: history-graph
        title: Last 24 Hours
        entities:
          - entity: climate.pool_heater    
        hours_to_show: 24
  - badges: []
    title: History
    panel: true
    icon: 'mdi:chart-line'
    cards:    
      - type: horizontal-stack
        cards:
          - title: Last Hour
            entities:
              - entity: switch.pump
                name: Pump
              - entity: switch.orp
                name: Bleach inj.
              - entity: switch.ph
                name: Muriatic inj.
              - entity: sensor.pre_filter_temp
                name: Pre-Filter Temp
              - entity: sensor.orp_mean
                name: ORP
              - entity: sensor.ph_mean
                name: pH
            type: history-graph
            hours_to_show: 1
          - title: Last 6 Hours
            entities:
              - entity: switch.pump
                name: Pump
              - entity: switch.orp
                name: Bleach inj.
              - entity: switch.ph
                name: Muriatic inj.
              - entity: sensor.pre_filter_temp
                name: Pre-Filter Temp
              - entity: sensor.orp_mean
                name: ORP
              - entity: sensor.ph_mean
                name: pH
            type: history-graph
            hours_to_show: 6
          - title: Last 3 Days
            entities:
              - entity: switch.pump
                name: Pump
              - entity: switch.orp
                name: Bleach inj.
              - entity: switch.ph
                name: Muriatic inj.
              - entity: sensor.pre_filter_temp
                name: Pre-Filter Temp    
              - entity: sensor.orp_mean
                name: ORP
              - entity: sensor.ph_mean
                name: pH
            type: history-graph
            hours_to_show: 172
  - badges: []
    title: Chemical
    panel: true
    icon: 'mdi:flask'
    cards:
      - type: horizontal-stack
        cards:
          - entities:
              - label: Muriatic ( - pH )
                type: section
              - entity: input_number.muriatic_tank
                name: Tank level
              - entity: input_number.muriatic_concentration
                name: Concentration
              - entity: input_number.muriatic_speed
                name: Speed injection
              - entity: switch.ph
                name: Pump injection
                secondary_info: last-changed
              - entity: input_boolean.lock_muriatic
                name: Lock Pump
            type: entities
            show_header_toggle: false
          - entities:
              - label: Bleach ( + ORP )
                type: section
              - entity: input_number.bleach_tank
                name: Tank level
              - entity: input_number.bleach_concentration
                name: Concentration
              - entity: input_number.bleach_speed
                name: Speed injection
              - entity: switch.orp
                name: Pump injection
                secondary_info: last-changed
              - entity: input_boolean.lock_bleach
                name: Lock Pump
            type: entities
            show_header_toggle: false
  - badges: []
    path: default_view
    icon: 'mdi:message-alert'
    title: Alerts
    cards:
      - title: Notifications
        entities:
          - entity: input_number.notify_cycles
          - entity: input_boolean.notify_seasson
          - entity: input_number.notify_muriatic_high
          - entity: input_number.notify_bleach_high
          - entity: input_number.notify_muriatic_tank
          - entity: input_number.notify_bleach_tank
        type: entities
        show_header_toggle: true
  - badges: []
    title: Settings
    icon: 'mdi:tune'
    cards:
      - title: Pool Settings
        entities:
          - label: Pool
            type: section
          - entity: input_boolean.summer_mode
            name: Summer Mode
          - entity: input_number.capacity
            name: Capacity
          - entity: input_number.quality
            name: Quality
#          - entity: input_datetime.recirculation
#          - entity: input_number.recirculation_time
#            name: Turnover rate
#          - entity: input_boolean.turbo
#          - entity: input_number.turbo
#Below inputs are added for testing new logic
#          - entity: input_number.pump_on_for
          - label: Filter
            type: section
          - entity: input_datetime.cycle_start
          - entity: input_number.first_cycle
          - entity: input_number.cycle_delay
          - entity: input_number.second_cycle
          - entity: sensor.cycle_pool
          - entity: input_number.cycle
#Below inputs are added for testing new logic          
#          - entity: input_number.recirculation_time
#          - entity: input_number.cycles_per_day
        type: entities
        show_header_toggle: false
        theme: default
      - title: Chemical settings
        entities:
          - label: Free Chlorine (FC)
            type: section
          - entity: input_number.fc_target
            name: FC target
          - entity: sensor.e_fc
            name: FC actual
          - entity: input_number.bleach_inject
            name: Next bleach injection (ml)
          - entity: input_number.e_fc_adjust
            name: Adjust ±% FC-ORP
          - label: pH
            type: section
          - entity: input_number.ph_target
            name: pH target
          - entity: sensor.ph_mean
            name: pH actual
          - entity: input_number.muriatic_inject
            name: Next muriatic injection (ml)
          - label: ORP
            type: section
          - entity: input_number.orp_target
        type: entities
        show_header_toggle: false
  - badges:
      - sun.sun
      - sensor.time
      - sensor.cycle_pool
      - sensor.raspipool_panel_temp
      - input_number.out_of_order
    title: Advanced
    panel: false
    icon: 'mdi:cog'
    cards:
      - type: horizontal-stack
        cards:
          - icon_height: 72px
            type: entity-button
            tap_action:
              action: none
            entity: input_number.out_of_order
            show_name: true
            name: Maintenance
            show_icon: true
            hold_action:
              action: more-info
          - icon_height: 72px
            type: entity-button
            tap_action:
              action: more-info
            entity: input_datetime.cummulated_flow_start
            show_name: true
            name: Reset Cumm. Flow
            show_icon: true
            hold_action:
              action: call-service
              service: automation.trigger
              service_data:
                entity_id: automation.reset_cummulated_flow_start
          - icon_height: 72px
            type: entity-button
            tap_action:
              action: none
            entity: input_number.pump_on_for
            show_name: true
            name: Filter for ...
            show_icon: true
            hold_action:
              action: more-info
      - entities:
          - entity: input_datetime.cummulated_flow_start
          - entity: sensor.cummulated_flow_high
          - entity: sensor.cummulated_flow_low
        type: entities
