sensor:
  - platform: atlas_scientific
# For serial ports use:
    port: /dev/ttyAMA0
# For I2C enter the hex device id
#    port: 0x62
#    offset: 78
    scan_interval: 180

  - platform: statistics
    name: orp_mean
    entity_id: sensor.ezo_orp
    state_characteristic: mean
    max_age:
      minutes: 60
    precision: 1

input_number:
  orp_target:
    min: 600
    max: 800
    step: 0.01
    unit_of_measurement: 'mV'
    icon: mdi:alpha-r-circle-outline
    mode: box
    name: Target ORP
    
automation:
- alias: orp_start
  id: '1559639825764'
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.orp
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.pump
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.orp

- alias: orp_bad
  id: '1559149493756'
  initial_state: true
  trigger:
  - platform: template
    value_template: '{{state_attr("sensor.orp_mean", "standard_deviation") > 20 }}'
  condition: []
  action:
# - service: notify.pushbullet
  - service: notify.jason
    data_template:
      message: 'Between {{state_attr("sensor.orp_mean", "min_value")}} and {{state_attr("sensor.orp_mean", "max_value")}}{{- "\n\n" -}}@{{now().strftime("%H:%M")}}[{{now().day}}/{{now().month}}]'
      title: 'ORP probe bad (calibrate?) !!!'
  - service: automation.turn_off
    entity_id: automation.orp_bad
