input_datetime:
  cycle_start:
    name: Pump cycle start time
    has_date: false
    has_time: true
  recirculation:
    name: Recirculation cycle
    has_time: true
    has_date: false
    icon: mdi:timer


input_number:
  capacity:
    name: Pool capacity (gal)
    min: 1000
    max: 20000
    unit_of_measurement: gal
    mode: box
    icon: mdi:water-pump
  quality:
    name: Pool quality
    min: 0
    max: 9
    unit_of_measurement: stars
    icon: mdi:star
  turbo:
    name: '% in high speed'
    min: 0
    max: 100
    step: 5
    unit_of_measurement: '%'
    icon: mdi:circle-slice-2
#Items below added for new pump control testing    
  recirculation_time:
    name: Recirculation Time
    min: 0
    max: 1440
    step: 10
    unit_of_measurement: 'Minutes'
    mode: box
    icon: mdi:clock   
  cycles_per_day:
    name: Pump Cycles Per Day
    min: 0
    max: 10
    step: .5
    unit_of_measurement: 'Cycles'
    mode: box
    icon: mdi:counter


input_boolean:
  turbo:
    name: Dual-speed Pump
    icon: mdi:play-speed
  
  factory_started:
    name: Factory config started
    icon: mdi:auto-fix


automation:
- alias: factory_started
  id: '1559149839000'
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  condition: 
    condition: state 
    entity_id: input_boolean.factory_started
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.factory_started
  - service: input_number.set_value
    data_template:
      entity_id: input_number.capacity
      value: 14500
  - service: input_number.set_value
    data_template:
      entity_id: input_number.quality
      value: 7
  - service: input_number.set_value
    data_template:
      entity_id: input_number.bleach_tank
      value: 20
  - service: input_number.set_value
    data_template:
      entity_id: input_number.bleach_concentration
      value: 5
  - service: input_number.set_value
    data_template:
      entity_id: input_number.bleach_speed
      value: 25
  - service: input_number.set_value
    data_template:
      entity_id: input_number.fc_target
      value: 1.5
  - service: input_number.set_value
    data_template:
      entity_id: input_number.e_fc_adjust
      value: 0
  - service: input_number.set_value
    data_template:
      entity_id: input_number.ph_target
      value: 7.6
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_tank
      value: 10
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_concentration
      value: 20
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_speed
      value: 25



